### ISSUE TITLE
MVP for public launch of docs website

### ISSUE THREAD

**Issue by zramsay** [LaconicNetwork/docs.laconic.com#97]
- [ ] polish & smoke test stack tutorial (somewhat blocking on eg https://github.com/cerc-io/stack-orchestrator/issues/70
- [ ] remove Glossary (needs a ton of work, so items to be re-introduced slowly)
- [ ] polish FAQ (has lots of good info, high ROI on updating it)
- [ ] style changes cc @rickmanelius (e.g. more contrast in code blocks)
- [ ] host docs.laconic.com on IPFS (https://github.com/vulcanize/ops/issues/210)
- [ ] dark mode (#94) - not required but ideal
- [ ] disable search - doesn't work

**Comment by zramsay** [comment]
outdated, new MVP is progressing nicely
